### PR TITLE
vendor: Add Vault API deps

### PR DESCRIPTION
**Pull request by rossf7**
- Add vault/api deps for Vault 0.6.5

### CODE REVIEW

**Comment by w0mbat** [comment]
Do we need the vendor folder in there?

**Comment by JosephSalisbury** [comment]
How else would we add dependencies?

**Comment by rossf7** [comment]
Afraid so even with golang/dep when its ready!  :)

**Comment by w0mbat** [comment]
@JosephSalisbury Still always wondering, why glide/golang has to package all deps into the repo - coming from the Java ecosystem makes this feel weird but its offtopic ;)

**Comment by rossf7** [comment]
@w0mbat I used to do a lot of Ruby so vendor/ is also a bit strange for me ;)

The convention is to commit vendor/ and I'm trying to follow the structure of aws-operator and kvm-operator where possible.

**Pull request merged**
