### PR TITLE
Docs for running cert-operator locally

### LINKED ISSUE #40: Docs for running cert-operator locally

### PR DESCRIPTION
**Pull request by rossf7**
Fixes #40 

Adds docs for running the operator locally. Also helps with running aws-operator locally as the example cert TPOs match the example cluster TPO.

### CODE REVIEW

**Comment by kopiczko** [comment]
@rossf7 why not include vault.yml in examples?

**Comment by rossf7** [comment]
@kopiczko can you delete the operator pod and try again? I've seen that problem the first time it runs with creating the TPR.

On vault.yml being in /examples/ I thought it was simpler as a gist but I don't have a strong opinion. Currently we have to use Vault 0.6.4 due to `certctl` but we'll need to upgrade to Vault 0.7 for the Kubernetes 1.6 upgrade.

**Comment by kopiczko** [comment]
@rossf7 
1. I have to delete pod every time after deployment on a fresh cluster, bc of `Failed to list *certificatetpr.CustomObject`
2. I lost some time on realising I need to replace YOUR_VAULT_HOST. While obvious now it may save some time other folks if this is stated in the readme.

**Comment by rossf7** [comment]
@kopiczko sorry I've added a note on editing YOUR_VAULT_HOST. I also added the delete pod step so the new docker image is used.

I'll look into the startup bug with the TPR.

**Comment by asymmetric** [comment]
I agree that the Vault config should be in `examples/`.

**Comment by kopiczko** [comment]
Maybe create `local-vault.yml` and `local-deployment.yml` in examples  & replace YOUR_VAULT_HOST with `vault` as service is in place.

That'd be our default way to set local cert-operator.

Let me know your thoughts.

**Comment by rossf7** [comment]
@kopiczko the problem with using the service hostname is then you also need `kube-dns` running on your local cluster. So it adds another dependency.

This is a simple setup for local testing. For pull based deployments hopefully it will support local targets. That would be useful for local testing and we could stop using this manual setup.

cc @JosephSalisbury

**Comment by rossf7** [comment]
I've created #44 for the startup error.

**Pull request merged**
