### PR TITLE
look for clusters in all namespaces

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards: https://github.com/giantswarm/giantswarm/issues/12647

When checking if a cluster still exists, we want to check all namespaces and not just the `default` one.

## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by stone-z — APPROVED** [review]
LGTM

**Review by MarcelMue — COMMENTED** [review]
Let's not just merge this here but coordinate with the ongoing release:
https://github.com/giantswarm/cert-operator/pull/328

**Comment by anvddriesch** [comment]
Sure, I'm not in a hurry with this.

**Comment by xh3b4sd** [comment]
Was the ongoing release sorted out at some point? 🙈 😅

**Comment by MarcelMue** [comment]
> Was the ongoing release sorted out at some point? see_no_evil sweat_smile

We have this on our Ludacris board to test and get done. It's just that other priorities were higher so far.

**Comment by stone-z** [comment]
@anvddriesch we're ready to release `cert-operator` if you'd still like to include this

**Comment by anvddriesch** [comment]
Sure. Are you fine if I just merge it?

**Comment by stone-z** [comment]
> Sure. Are you fine if I just merge it?

If it does what you need and still works for `default` then ok with me

**Pull request merged**
