### PR TITLE
Manage Secrets in the same namespace in which CertConfigs are found

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/roadmap/issues/103
## Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by calvix — APPROVED** [review]
looks sane to me

**Review by stone-z — COMMENTED** [review]
This seems ok to me. Have you already tested creation and update from the previous cert-operator?

**Comment by anvddriesch** [comment]
Cluster creation in another namespace appears to work now with this (in combination with changes in a few other repos). I still need to test the creation and update of clusters in `default` namespace.

**Comment by anvddriesch** [comment]
Tested in `ginger`, all good.

**Pull request merged**
